package com.dualmusic.domain.geo

/**
 * Pays sélectionnable (inscription, édition de profil).
 *
 * @property code code ISO-2 (envoyé au backend en `countryCode`, ex. `CI`).
 * @property name nom affiché.
 * @property dial indicatif téléphonique (envoyé en `phoneCountryCode`, ex. `+225`).
 */
data class Country(val code: String, val name: String, val dial: String)

/**
 * Liste (curatée) des pays — marchés cibles de Dual Music (Afrique francophone + Europe +
 * quelques grands marchés). Partagée entre l'inscription et l'édition de profil. Défaut : France.
 */
object Countries {
    val ALL: List<Country> = listOf(
        Country("CI", "Côte d'Ivoire", "+225"),
        Country("SN", "Sénégal", "+221"),
        Country("CM", "Cameroun", "+237"),
        Country("ML", "Mali", "+223"),
        Country("BF", "Burkina Faso", "+226"),
        Country("BJ", "Bénin", "+229"),
        Country("TG", "Togo", "+228"),
        Country("NE", "Niger", "+227"),
        Country("GN", "Guinée", "+224"),
        Country("CG", "Congo", "+242"),
        Country("CD", "RD Congo", "+243"),
        Country("GA", "Gabon", "+241"),
        Country("TD", "Tchad", "+235"),
        Country("MG", "Madagascar", "+261"),
        Country("CF", "Centrafrique", "+236"),
        Country("MR", "Mauritanie", "+222"),
        Country("MA", "Maroc", "+212"),
        Country("DZ", "Algérie", "+213"),
        Country("TN", "Tunisie", "+216"),
        Country("NG", "Nigeria", "+234"),
        Country("GH", "Ghana", "+233"),
        Country("FR", "France", "+33"),
        Country("BE", "Belgique", "+32"),
        Country("CH", "Suisse", "+41"),
        Country("LU", "Luxembourg", "+352"),
        Country("CA", "Canada", "+1"),
        Country("US", "États-Unis", "+1"),
        Country("GB", "Royaume-Uni", "+44"),
        Country("DE", "Allemagne", "+49"),
        Country("ES", "Espagne", "+34"),
        Country("IT", "Italie", "+39"),
        Country("PT", "Portugal", "+351"),
    )

    /**
     * Liste MONDIALE complète (parité stricte avec `src/data/countries.ts` du web : même ordre,
     * mêmes codes ISO, noms FR). Utilisée par le sélecteur d'éligibilité des compétitions.
     */
    val WORLD: List<Country> = listOf(
        Country("AF", "Afghanistan", "+93"),
        Country("ZA", "Afrique du Sud", "+27"),
        Country("AL", "Albanie", "+355"),
        Country("DZ", "Algérie", "+213"),
        Country("DE", "Allemagne", "+49"),
        Country("AD", "Andorre", "+376"),
        Country("AO", "Angola", "+244"),
        Country("AG", "Antigua-et-Barbuda", "+1-268"),
        Country("SA", "Arabie Saoudite", "+966"),
        Country("AR", "Argentine", "+54"),
        Country("AM", "Arménie", "+374"),
        Country("AU", "Australie", "+61"),
        Country("AT", "Autriche", "+43"),
        Country("AZ", "Azerbaïdjan", "+994"),
        Country("BS", "Bahamas", "+1-242"),
        Country("BH", "Bahreïn", "+973"),
        Country("BD", "Bangladesh", "+880"),
        Country("BB", "Barbade", "+1-246"),
        Country("BY", "Biélorussie", "+375"),
        Country("BE", "Belgique", "+32"),
        Country("BZ", "Belize", "+501"),
        Country("BJ", "Bénin", "+229"),
        Country("BT", "Bhoutan", "+975"),
        Country("BO", "Bolivie", "+591"),
        Country("BA", "Bosnie-Herzégovine", "+387"),
        Country("BW", "Botswana", "+267"),
        Country("BR", "Brésil", "+55"),
        Country("BN", "Brunéi", "+673"),
        Country("BG", "Bulgarie", "+359"),
        Country("BF", "Burkina Faso", "+226"),
        Country("BI", "Burundi", "+257"),
        Country("CV", "Cap-Vert", "+238"),
        Country("KH", "Cambodge", "+855"),
        Country("CM", "Cameroun", "+237"),
        Country("CA", "Canada", "+1"),
        Country("CF", "Centrafrique", "+236"),
        Country("CL", "Chili", "+56"),
        Country("CN", "Chine", "+86"),
        Country("CY", "Chypre", "+357"),
        Country("CO", "Colombie", "+57"),
        Country("KM", "Comores", "+269"),
        Country("CG", "Congo", "+242"),
        Country("CD", "Congo (RDC)", "+243"),
        Country("KR", "Corée du Sud", "+82"),
        Country("KP", "Corée du Nord", "+850"),
        Country("CR", "Costa Rica", "+506"),
        Country("CI", "Côte d'Ivoire", "+225"),
        Country("HR", "Croatie", "+385"),
        Country("CU", "Cuba", "+53"),
        Country("DK", "Danemark", "+45"),
        Country("DJ", "Djibouti", "+253"),
        Country("DM", "Dominique", "+1-767"),
        Country("EG", "Égypte", "+20"),
        Country("AE", "Émirats Arabes Unis", "+971"),
        Country("EC", "Équateur", "+593"),
        Country("ER", "Érythrée", "+291"),
        Country("ES", "Espagne", "+34"),
        Country("EE", "Estonie", "+372"),
        Country("SZ", "Eswatini", "+268"),
        Country("US", "États-Unis", "+1"),
        Country("ET", "Éthiopie", "+251"),
        Country("FJ", "Fidji", "+679"),
        Country("FI", "Finlande", "+358"),
        Country("FR", "France", "+33"),
        Country("GA", "Gabon", "+241"),
        Country("GM", "Gambie", "+220"),
        Country("GE", "Géorgie", "+995"),
        Country("GH", "Ghana", "+233"),
        Country("GR", "Grèce", "+30"),
        Country("GD", "Grenade", "+1-473"),
        Country("GT", "Guatemala", "+502"),
        Country("GN", "Guinée", "+224"),
        Country("GW", "Guinée-Bissau", "+245"),
        Country("GQ", "Guinée Équatoriale", "+240"),
        Country("GY", "Guyana", "+592"),
        Country("HT", "Haïti", "+509"),
        Country("HN", "Honduras", "+504"),
        Country("HU", "Hongrie", "+36"),
        Country("IN", "Inde", "+91"),
        Country("ID", "Indonésie", "+62"),
        Country("IQ", "Irak", "+964"),
        Country("IR", "Iran", "+98"),
        Country("IE", "Irlande", "+353"),
        Country("IS", "Islande", "+354"),
        Country("IL", "Israël", "+972"),
        Country("IT", "Italie", "+39"),
        Country("JM", "Jamaïque", "+1-876"),
        Country("JP", "Japon", "+81"),
        Country("JO", "Jordanie", "+962"),
        Country("KZ", "Kazakhstan", "+7"),
        Country("KE", "Kenya", "+254"),
        Country("KG", "Kirghizistan", "+996"),
        Country("KI", "Kiribati", "+686"),
        Country("KW", "Koweït", "+965"),
        Country("LA", "Laos", "+856"),
        Country("LS", "Lesotho", "+266"),
        Country("LV", "Lettonie", "+371"),
        Country("LB", "Liban", "+961"),
        Country("LR", "Libéria", "+231"),
        Country("LY", "Libye", "+218"),
        Country("LI", "Liechtenstein", "+423"),
        Country("LT", "Lituanie", "+370"),
        Country("LU", "Luxembourg", "+352"),
        Country("MG", "Madagascar", "+261"),
        Country("MY", "Malaisie", "+60"),
        Country("MW", "Malawi", "+265"),
        Country("MV", "Maldives", "+960"),
        Country("ML", "Mali", "+223"),
        Country("MT", "Malte", "+356"),
        Country("MA", "Maroc", "+212"),
        Country("MH", "Marshall (Îles)", "+692"),
        Country("MU", "Maurice", "+230"),
        Country("MR", "Mauritanie", "+222"),
        Country("MX", "Mexique", "+52"),
        Country("FM", "Micronésie", "+691"),
        Country("MD", "Moldavie", "+373"),
        Country("MC", "Monaco", "+377"),
        Country("MN", "Mongolie", "+976"),
        Country("ME", "Monténégro", "+382"),
        Country("MZ", "Mozambique", "+258"),
        Country("MM", "Myanmar", "+95"),
        Country("NA", "Namibie", "+264"),
        Country("NR", "Nauru", "+674"),
        Country("NP", "Népal", "+977"),
        Country("NI", "Nicaragua", "+505"),
        Country("NE", "Niger", "+227"),
        Country("NG", "Nigéria", "+234"),
        Country("NO", "Norvège", "+47"),
        Country("NZ", "Nouvelle-Zélande", "+64"),
        Country("OM", "Oman", "+968"),
        Country("UG", "Ouganda", "+256"),
        Country("UZ", "Ouzbékistan", "+998"),
        Country("PK", "Pakistan", "+92"),
        Country("PW", "Palaos", "+680"),
        Country("PA", "Panama", "+507"),
        Country("PG", "Papouasie-Nouvelle-Guinée", "+675"),
        Country("PY", "Paraguay", "+595"),
        Country("NL", "Pays-Bas", "+31"),
        Country("PE", "Pérou", "+51"),
        Country("PH", "Philippines", "+63"),
        Country("PL", "Pologne", "+48"),
        Country("PT", "Portugal", "+351"),
        Country("QA", "Qatar", "+974"),
        Country("RO", "Roumanie", "+40"),
        Country("GB", "Royaume-Uni", "+44"),
        Country("RU", "Russie", "+7"),
        Country("RW", "Rwanda", "+250"),
        Country("KN", "Saint-Kitts-et-Nevis", "+1-869"),
        Country("LC", "Saint-Lucie", "+1-758"),
        Country("VC", "Saint-Vincent-et-les-Grenadines", "+1-784"),
        Country("SB", "Salomon (Îles)", "+677"),
        Country("WS", "Samoa", "+685"),
        Country("ST", "Sao Tomé-et-Principe", "+239"),
        Country("SN", "Sénégal", "+221"),
        Country("RS", "Serbie", "+381"),
        Country("SC", "Seychelles", "+248"),
        Country("SL", "Sierra Leone", "+232"),
        Country("SG", "Singapour", "+65"),
        Country("SK", "Slovaquie", "+421"),
        Country("SI", "Slovénie", "+386"),
        Country("SO", "Somalie", "+252"),
        Country("SD", "Soudan", "+249"),
        Country("SS", "Soudan du Sud", "+211"),
        Country("LK", "Sri Lanka", "+94"),
        Country("SE", "Suède", "+46"),
        Country("CH", "Suisse", "+41"),
        Country("SR", "Suriname", "+597"),
        Country("SY", "Syrie", "+963"),
        Country("TJ", "Tadjikistan", "+992"),
        Country("TZ", "Tanzanie", "+255"),
        Country("TD", "Tchad", "+235"),
        Country("CZ", "Tchéquie", "+420"),
        Country("TH", "Thaïlande", "+66"),
        Country("TL", "Timor-Leste", "+670"),
        Country("TG", "Togo", "+228"),
        Country("TO", "Tonga", "+676"),
        Country("TT", "Trinité-et-Tobago", "+1-868"),
        Country("TN", "Tunisie", "+216"),
        Country("TM", "Turkménistan", "+993"),
        Country("TR", "Turquie", "+90"),
        Country("TV", "Tuvalu", "+688"),
        Country("UA", "Ukraine", "+380"),
        Country("UY", "Uruguay", "+598"),
        Country("VU", "Vanuatu", "+678"),
        Country("VE", "Venezuela", "+58"),
        Country("VN", "Vietnam", "+84"),
        Country("YE", "Yémen", "+967"),
        Country("ZM", "Zambie", "+260"),
        Country("ZW", "Zimbabwe", "+263"),
    )

    /** Pays par défaut (France). */
    val DEFAULT: Country = ALL.first { it.code == "FR" }

    /** Retrouve un pays par son code ISO-2, sinon [DEFAULT]. */
    fun byCode(code: String?): Country = ALL.firstOrNull { it.code == code } ?: DEFAULT

    /** Retrouve un pays par son indicatif (`+225`), sinon `null`. */
    fun byDial(dial: String?): Country? = ALL.firstOrNull { it.dial == dial }
}
