# Options JVM du démon Gradle (mémoire suffisante pour Compose).
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX obligatoire.
android.useAndroidX=true

# Kotlin officiel.
kotlin.code.style=official

# Build en parallèle + cache (accélère les compilations).
org.gradle.parallel=true
org.gradle.caching=true
